# Generated by Django 5.0.14 on 2026-04-03 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('items', '0001_initial'),
        ('procurement', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceiptPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grpo_number', models.CharField(max_length=20, unique=True)),
                ('receipt_date', models.DateField()),
                ('posting_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='AWB/BL or tracking reference', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('total_cartons_received', models.IntegerField(default=0)),
                ('total_cbm_received', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ppo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipts', to='procurement.plannedpurchaseorder')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Goods Receipt PO',
                'verbose_name_plural': 'Goods Receipt POs',
                'ordering': ['-receipt_date'],
            },
        ),
        migrations.CreateModel(
            name='GRPOLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_expected', models.IntegerField()),
                ('quantity_received', models.IntegerField()),
                ('quantity_damaged', models.IntegerField(default=0)),
                ('quantity_accepted', models.IntegerField(default=0)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('grpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='receiving.goodsreceiptpo')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('ppo_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grpo_lines', to='procurement.ppolineitem')),
            ],
        ),
    ]
