# Generated by Django 5.0.14 on 2026-04-03 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppo_number', models.IntegerField(unique=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent_to_vendor', 'Sent to Vendor'), ('pi_received', 'PI Received'), ('pending_ceo_approval', 'Pending CEO Approval'), ('ceo_approved', 'CEO Approved'), ('ceo_rejected', 'CEO Rejected'), ('confirmed', 'Confirmed/Active'), ('in_transit', 'In Transit'), ('partially_received', 'Partially Received'), ('fully_received', 'Fully Received'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('requested_ship_date', models.DateField(blank=True, null=True)),
                ('estimated_ship_date', models.DateField(blank=True, null=True)),
                ('actual_ship_date', models.DateField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=100)),
                ('mode_of_transport', models.CharField(choices=[('container', 'Container'), ('air', 'Air Freight'), ('express', 'Express/Courier'), ('lcl', 'LCL (Less than Container)'), ('truck', 'Truck')], default='container', max_length=20)),
                ('port_of_loading', models.CharField(blank=True, max_length=200)),
                ('port_of_discharge', models.CharField(blank=True, max_length=200)),
                ('country_of_origin', models.CharField(blank=True, max_length=100)),
                ('incoterms', models.CharField(choices=[('DDP', 'DDP - Delivered Duty Paid'), ('FOB', 'FOB - Free on Board'), ('CIF', 'CIF - Cost Insurance Freight'), ('EXW', 'EXW - Ex Works'), ('CFR', 'CFR - Cost and Freight'), ('DAP', 'DAP - Delivered at Place')], default='DDP', max_length=3)),
                ('lead_time_days', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('awb_bl_number', models.CharField(blank=True, max_length=100, verbose_name='AWB/BL #')),
                ('special_notes', models.TextField(blank=True)),
                ('wire_info', models.TextField(blank=True, help_text='Factory wire/bank information')),
                ('total_cartons', models.IntegerField(default=0)),
                ('total_cbm', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='ppo_pdfs/')),
                ('vendor_email_sent_date', models.DateTimeField(blank=True, null=True)),
                ('ceo_approval_requested_date', models.DateTimeField(blank=True, null=True)),
                ('ceo_approval_date', models.DateTimeField(blank=True, null=True)),
                ('ceo_rejection_reason', models.TextField(blank=True)),
                ('vendor_pi_number', models.CharField(blank=True, help_text="Vendor's PI reference number", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.billtoaddress')),
                ('ceo_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppos_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppos_created', to=settings.AUTH_USER_MODEL)),
                ('ship_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.shiptoaddress')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-ppo_number'],
            },
        ),
        migrations.CreateModel(
            name='PPOAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ppo_attachments/')),
                ('file_type', models.CharField(choices=[('pi_document', 'Proforma Invoice'), ('signed_ppo', 'Signed PPO'), ('ceo_approval', 'CEO Approval'), ('shipping_doc', 'Shipping Document'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ppo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='procurement.plannedpurchaseorder')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PPOLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cartons', models.IntegerField(blank=True, null=True)),
                ('cbm', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('total_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('destination', models.CharField(blank=True, help_text='e.g., Shopify, Amazon, Walmart', max_length=200)),
                ('qty_received', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('ppo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.plannedpurchaseorder')),
            ],
            options={
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='PPOStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ppo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='procurement.plannedpurchaseorder')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProformaInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pi_number', models.CharField(help_text="Vendor's PI number (usually PO followed by number)", max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('received', 'Received'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='received', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('file', models.FileField(help_text='Upload the PI document from vendor', upload_to='proforma_invoices/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ppo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proforma_invoices', to='procurement.plannedpurchaseorder')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_number', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('converted', 'Converted to PPO'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_approved', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='plannedpurchaseorder',
            name='purchase_requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.purchaserequisition'),
        ),
        migrations.CreateModel(
            name='PurchaseRequisitionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.purchaserequisition')),
                ('suggested_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.vendor')),
            ],
        ),
    ]
