# Generated by Django 5.0.14 on 2026-04-03 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
        ('vendors', '0002_branch_threeplprovider_alter_vendor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedpurchaseorder',
            name='branch',
            field=models.ForeignKey(help_text='MTB, Spa Sciences, or NasalFresh MD', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.branch'),
        ),
        migrations.AddField(
            model_name='plannedpurchaseorder',
            name='ship_to_3pl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.threeplprovider', verbose_name='Ship To (3PL)'),
        ),
        migrations.AlterField(
            model_name='plannedpurchaseorder',
            name='ship_to',
            field=models.ForeignKey(blank=True, help_text='Legacy - use 3PL instead', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.shiptoaddress'),
        ),
    ]
