# Generated by Django 5.0.14 on 2026-04-04 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_plannedpurchaseorder_branch_and_more'),
        ('vendors', '0002_branch_threeplprovider_alter_vendor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedpurchaseorder',
            name='bill_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.billtoaddress'),
        ),
        migrations.AlterField(
            model_name='plannedpurchaseorder',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='MTB, Spa Sciences, or NasalFresh MD', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.branch'),
        ),
        migrations.AlterField(
            model_name='ppolineitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ppolineitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
