# Generated by Django 5.0.14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_alter_plannedpurchaseorder_bill_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedpurchaseorder',
            name='ceo_signature_type',
            field=models.CharField(blank=True, choices=[('typed', 'Typed'), ('image', 'Uploaded Image')], help_text='How the CEO signed', max_length=10),
        ),
        migrations.AddField(
            model_name='plannedpurchaseorder',
            name='ceo_signature_text',
            field=models.CharField(blank=True, help_text='Typed signature name', max_length=200),
        ),
        migrations.AddField(
            model_name='plannedpurchaseorder',
            name='ceo_signature_image',
            field=models.ImageField(blank=True, help_text='Uploaded signature image', null=True, upload_to='signatures/'),
        ),
    ]
