# Generated by Django 5.0.14 on 2026-04-03 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('in_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_purchase_date', models.DateField(blank=True, null=True)),
                ('qty_ordered_by_customers', models.IntegerField(default=0)),
                ('abc_classification', models.CharField(blank=True, choices=[('A', 'A - High Volume'), ('C', 'C - Low Volume'), ('D', 'D - Phase-In'), ('E', 'E - Phase-Out'), ('F', 'F - Other'), ('I', 'I - Ind. Comp.')], max_length=2)),
                ('qty_ordered_from_vendors', models.IntegerField(default=0)),
                ('property_1', models.CharField(blank=True, default='No', max_length=100)),
                ('property_2', models.CharField(blank=True, default='No', max_length=100)),
                ('height_uom', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('length_uom', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width_uom', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight_uom', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('superseding_item', models.CharField(blank=True, max_length=50)),
                ('upc_inner_carton_qty', models.IntegerField(default=0)),
                ('upc_master_carton_qty', models.IntegerField(default=0)),
                ('master_carton_volume', models.DecimalField(decimal_places=6, default=0, help_text='Volume in cubic inches', max_digits=12)),
                ('issue_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('height_purchasing_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inactive', models.BooleanField(default=False)),
                ('branch', models.CharField(blank=True, help_text='Michael Todd Beauty, Spa Sciences, NasaFresh MD', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse')),
            ],
            options={
                'ordering': ['item_no'],
            },
        ),
    ]
